version: '3.5'

services:
  
  api:
    container_name: mvn
    ports:
      - "9003:9003"
    build: ./backend
    depends_on:
      - cassandra
    networks:
      - host

  webapp:
    container_name: node
    build: ./frontend
    environment:
      - API_URL=http://13.53.235.85:9003/api/text_field_1/Abduljawad
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - public_network


  cassandra:
      image: cassandra:latest
      container_name: cassandra
      ports:
        - "9042:9042"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
      restart: always
      volumes:
        - ./backend/src/main/resources/data.cql:/schema.cql 
        - ./out/cassandra_data:/var/lib/cassandra
      networks:
        - public_network

  cassandra-load-keyspace:
      container_name: cassandra-load-keyspace
      image: cassandra:latest
      depends_on:
        - cassandra
      volumes:
        - ./backend/src/main/resources/data.cql:/schema.cql 
      command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
      networks:
        - public_network
networks:
  public_network:      