version: "3.7"
services:

  backend:
   container_name:  backend
    build: 
       context: ./cassandra-maven
       args: 
            JAR_FILE:  /spring-boot-cassandra-0.0.1-SNAPSHOT.jar
    depends_on:
      - cassandra 
    networks:
      - cass-host

  frontend:
    build: ./frontend
    environment:
      - API_URL=http://backend:3001/data
    depends_on:
      -  backend
    ports:
      - "3000:3000"
    networks:
      - cass-host

  cassandra:
    image: cassandra
    container_name:  cassandra
    networks:
      - cass-host
    ports:
      - "9042:9042"
    networks:
      - cass-host

networks: 
  cass-host:
    driver: bridge

# networks:
#   public_network:      
version: "3.7"
services:

  backend:
   container_name:  backend
    build: 
       context: ./cassandra-maven
       args: 
            JAR_FILE:  /spring-boot-cassandra-0.0.1-SNAPSHOT.jar
    depends_on:
      - cassandra 
    networks:
      - cass-host

  frontend:
    build: ./frontend
    environment:
      - API_URL=http://backend:3001/data
    depends_on:
      -  backend
    ports:
      - "3000:3000"
    networks:
      - cass-host

  cassandra:
    image: cassandra
    container_name:  cassandra
    networks:
      - cass-host
    ports:
      - "9042:9042"
    networks:
      - cass-host

networks: 
  cass-host:
    driver: bridge