version: '3'

services:
  api:
    container_name: mvn
    build: ./backend
    depends_on:
      - "cassandra"
    environment:
       spring-boot: cassandra  
    ports:
      - 9003:9003
    networks:
      - public_network

  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
     - 9042:9042
    volumes:
      - ./backend/src/main/resources/data.cql:/schema.cql 
      - ./out/cassandra_data:/var/lib/cassandra
    networks:
      - public_network

  forntend:
    container_name: forntend
    build: ./frontend
    environment:
     - API_URL=http://api:9003/api/text_field_1/Abduljawad
    ports:
     - 3000:3000
    depends_on:
     - mvn
    networks:
     - public_network
networks:
  public_network: